# Firebase
NEXT_PUBLIC_FIREBASE_API_KEY =
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN =
    NEXT_PUBLIC_FIREBASE_PROJECT_ID =
    NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET =
    NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID =
    NEXT_PUBLIC_FIREBASE_APP_ID = your_app_id =

# Pusher
PUSHER_APP_ID =
    NEXT_PUBLIC_PUSHER_KEY =
    PUSHER_SECRET =
    NEXT_PUBLIC_PUSHER_CLUSTER =

# MongoDB
MONGODB_URI =
    MONGODB_ATLAS_URI =

# Cloudinary
NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME =
    NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET =
    CLOUDINARY_API_SECRET =
    CLOUDINARY_API_KEY =

# Gemini & Cloude
NEXT_PUBLIC_GEMINI_API_KEY =
    NEXT_PUBLIC_ANTHROPIC_API_KEY =

# RazorPay
RAZORPAY_KEY_SECRET =
    RAZORPAY_KEY_ID =
    NEXT_PUBLIC_RAZORPAY_KEY_ID =

# CertificateVerificationURL
NEXT_PUBLIC_CERTIFICATE_VERIFICATION_URL = http://localhost:3000

# GoogleMapApi(Dev)
NEXT_PUBLIC_GOOGLE_MAPS_API_KEY =& libraries=geometry & callback=initMap


